@startmindmap concepts
* Universe

** Domain

*** Domain Entity
**** Domain Entity Resolver

*** Domain State

*** Domain Event
**** Domain Event Parser

** Reality Engine

*** Higer-order Token
**** Null Token
**** Raw Token
**** Entity Token
***** Domain Entity Token
***** Common Entity Token
**** Intentity Token

*** Actor
**** Discrete Actor
**** Continuous Actor

*** Condenser
*** Transformer
*** Parser
@endmindmap